env:
  RUBY_VERSION: 2.6.5
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: postgres

name: Rails tests
on: [push, pull_request]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop rubocop-rails rubocop-rspec
      - name: Check code
        run: rubocop
  rspec-test:
    name: RSpec
    needs: rubocop-test
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          TEST_DB_DATABASE: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Montevideo
      - name: Run tests
        run: bundle exec rspec
        env:
          SECRET_KEY: 4afdb9edd83e171a491d6e4ab72099ee1da1323688984dcae7a2daafd6b53553f92167ffc0e1f2fc33bde129d68019b641d2335a1c1d2d446247343adf1e380f
          RAILS_ENV: test
          TEST_DB_DATABASE: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
